#!/bin/sh


if [ -z "$1" ]
  then
    PROG=demo.py
  else
    PROG="$1"
fi

if [ -z "$2" ]
  then
    SRC=easy
  else
    SRC="$2"
fi

LOC="/tmp/$LOGNAME/crushertest-$SRC"
HERE=`pwd`

rm -rf "$LOC"

mkdir -p "$LOC"
cd "$LOC"

"$HERE/$PROG" "/local/files/scrai002/csc456/input/$SRC.txt"
sed -e 's/^CAST	.*/CAST/' "$SRC-votelog.txt" > votelog.$$
sed -ne 's/^CAST	/INQ	/p' -e '/^CONF/p'  "$SRC-votelog.txt" > "$SRC.txt"
cp "$SRC-votelog.txt" votelog.txt
sort "$SRC-results.txt" > results.$$
"$HERE/$PROG" "$SRC.txt"

cat <<EOF
Votelog Errors: `diff votelog.$$ "/local/files/scrai002/csc456/correct/$SRC-votelog.txt" | wc -l`
Results Errors: `diff results.$$ "/local/files/scrai002/csc456/correct/$SRC-results.txt" | wc -l`
Inquiry Errors: `diff "votelog.txt" "$SRC-votelog.txt" | wc -l`
EOF
